### ISSUE TITLE
"当前账户已欠费？"

### ISSUE THREAD

**Issue by xushengmei** [vhall/VHYun_SDK_Android#1]
我在跑 demo 时，一开始提示包签名异常，现在提示 “当前账户已欠费”，实际上账户余额还是 100 ，这是怎么回事？ qq: 1252768410

**Comment by ZWPDean** [comment]
包签名异常：控制台配置的appId对应的包名、签名不统一；
关于账户余额100，提示欠费问题，请核对demo中配置的appid与当前控制台应用是否统一；
详细操作请前往官网http://www.vhall.com/ 联系客服处理。
